Repository LS-LEDA/MLA, pull requests merged in 2021-11, with the labels that each got.

#29 28/feat/routing
  package.json
  src/App.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationButton.vue
  src/main.js
  src/router/router.js
Labels: enhancement, Task

#30 21/feat/info pop up
  src/App.vue
  src/components/ImportData/DragDropArea.vue
  src/components/ImportData/InformationPopUp.vue
  src/pages/ImportData/ImportDataPage.vue
Labels: enhancement, Task

#31 17/feat/import data page
  src/App.vue
  src/components/ImportData/BrowseFilesButton.vue
  src/components/ImportData/DragDropArea.vue
  src/components/ImportData/InformationPopUp.vue
  src/components/ImportData/UploadConfirmation.vue
  src/components/ImportData/UploadProgressBar.vue
  src/components/UI/IconButton.vue
  src/pages/ImportData/ImportDataPage.vue
Labels: enhancement, Story

#33 32/fix/visual fixes
  src/App.vue
  src/components/ImportData/DragDropArea.vue
  src/components/ImportData/InformationPopUp.vue
  src/components/ImportData/UploadConfirmation.vue
  src/components/ImportData/UploadProgressBar.vue
  src/components/NavigationBar/NavigationBar.vue
  src/pages/ImportData/ImportDataPage.vue
  src/router/router.js
Labels: Task, Fix

#40 Navigation bar + Import Data Page
  package.json
  postcss.config.js
  public/assets/jsmla_logo.png
  src/App.vue
  src/components/ImportData/BrowseFilesButton.vue
  src/components/ImportData/DragDropArea.vue
  src/components/ImportData/InformationPopUp.vue
  src/components/ImportData/UploadConfirmation.vue
  src/components/ImportData/UploadProgressBar.vue
  src/components/NavigationBar/DownloadButton.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationButton.vue
  src/components/NavigationBar/NavigationHeader.vue
  src/components/UI/IconButton.vue
  src/index.css
  src/main.js
  src/pages/ImportData/ImportDataPage.vue
  src/router/router.js
  tailwind.config.js
Labels: enhancement, release

#42 39/feat/interaction card
  package.json
  src/assets/totalInteractionChartData.js
  src/components/Summary/InteractionCard.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/router/router.js
Labels: enhancement, Task

#43 37/feat/summary card back view
  src/components/Summary/SummaryCard.vue
  src/pages/Dashboard/Summary/Summary.vue
Labels: enhancement, Task

#44 38/feat/summary card
  package.json
  src/assets/totalInteractionChartData.js
  src/components/Summary/InteractionCard.vue
  src/components/Summary/SummaryCard.vue
  src/pages/Dashboard/DashboardPage.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/router/router.js
Labels: enhancement, Task

#45 Revert 44 38/feat/summary card
  package.json
  src/assets/totalInteractionChartData.js
  src/components/Summary/InteractionCard.vue
  src/pages/Dashboard/DashboardPage.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/router/router.js
Labels: enhancement, Task

#47 38/feat/summary card
  package.json
  src/assets/totalInteractionChartData.js
  src/components/Summary/InteractionCard.vue
  src/components/Summary/SummaryCard.vue
  src/pages/Dashboard/DashboardPage.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/router/router.js
Labels: enhancement, Task

#49 48/chore/routing electron
  .gitignore
  package.json
  public/index.html
  src/App.vue
  src/background.js
  src/components/NavigationBar/NavigationBar.vue
  src/components/Summary/SummaryCard.vue
  src/index.css
  src/pages/Dashboard/DashboardPage.vue
  src/router/router.js
Labels: enhancement, Task

#55 50/feat/minor enhancements
  package.json
  src/components/NavigationBar/DownloadButton.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationButton.vue
  src/components/NavigationBar/NavigationHeader.vue
  src/components/Summary/InteractionCard.vue
  src/components/Summary/SummaryCard.vue
  src/index.css
  src/main.js
  src/pages/Dashboard/DashboardPage.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/vuex/store.js
Labels: enhancement, Task, Fix

#56 v0.2.1 minor improvements
  .gitignore
  package.json
  public/index.html
  src/App.vue
  src/background.js
  src/components/NavigationBar/DownloadButton.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationButton.vue
  src/components/NavigationBar/NavigationHeader.vue
  src/components/Summary/InteractionCard.vue
  src/components/Summary/SummaryCard.vue
  src/index.css
  src/main.js
  src/pages/Dashboard/DashboardPage.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/router/router.js
  src/vuex/store.js
Labels: enhancement, Task, Fix

#61 #58 feat: imported sentiment file card
  src/components/Sentiment/SentimentFileCard.vue
Labels: enhancement, Task

#62 59/feat/sentiment overall
  src/assets/overallSentimentChartData.js
  src/components/Sentiment/SentimentOverallCard.vue
Labels: enhancement, Task

#63 60/feat/forum chat card
  src/components/Sentiment/SentimentChatCard.vue
  src/pages/Dashboard/Sentimental/Sentimental.vue
Labels: enhancement, Task

#65 #64 feat: Message score badge
  src/components/Sentiment/SentimentScore.vue
Labels: enhancement, Task

#66 57/feat/sentiment analysis page
  src/assets/overallSentimentChartData.js
  src/components/Sentiment/SentimentChatCard.vue
  src/components/Sentiment/SentimentFileCard.vue
  src/components/Sentiment/SentimentOverallCard.vue
  src/components/Sentiment/SentimentScore.vue
  src/pages/Dashboard/Sentimental/Sentimental.vue
Labels: enhancement, Story

#68 67/feat/sentiment analysis processing
  package.json
  src/assets/overallSentimentChartData.js
  src/components/ImportData/DragDropArea.vue
  src/components/ImportData/InformationPopUp.vue
  src/components/ImportData/UploadConfirmation.vue
  src/components/NavigationBar/DownloadButton.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationButton.vue
  src/components/NavigationBar/NavigationHeader.vue
  src/components/Sentiment/SentimentChatCard.vue
  src/components/Sentiment/SentimentFileCard.vue
  src/components/Sentiment/SentimentOverallCard.vue
  src/components/Sentiment/SentimentScore.vue
  src/components/Summary/InteractionCard.vue
  src/components/Summary/SummaryCard.vue
  src/pages/Dashboard/Sentimental/Sentimental.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/pages/ImportData/ImportDataPage.vue
  src/services/local-processing.js
  src/services/model/Message.js
  src/vuex/store.js
Labels: enhancement, Story

#70 69/feat/sentiment guard
  src/App.vue
  src/components/UI/Alert.vue
  src/router/router.js
  src/vuex/store.js
Labels: enhancement, Task

#71 Sentiment Analysis
  package.json
  src/App.vue
  src/assets/overallSentimentChartData.js
  src/components/ImportData/DragDropArea.vue
  src/components/ImportData/InformationPopUp.vue
  src/components/ImportData/UploadConfirmation.vue
  src/components/NavigationBar/DownloadButton.vue
  src/components/NavigationBar/NavigationBar.vue
  src/components/NavigationBar/NavigationButton.vue
  src/components/NavigationBar/NavigationHeader.vue
  src/components/Sentiment/SentimentChatCard.vue
  src/components/Sentiment/SentimentFileCard.vue
  src/components/Sentiment/SentimentOverallCard.vue
  src/components/Sentiment/SentimentScore.vue
  src/components/Summary/InteractionCard.vue
  src/components/Summary/SummaryCard.vue
  src/components/UI/Alert.vue
  src/pages/Dashboard/Sentimental/Sentimental.vue
  src/pages/Dashboard/Summary/Summary.vue
  src/pages/ImportData/ImportDataPage.vue
  src/router/router.js
  src/services/local-processing.js
  src/services/model/Message.js
  src/vuex/store.js
Labels: enhancement, Story

#76 75/feat/summary card processing
  src/pages/Dashboard/Summary/Summary.vue
  src/services/Summary/summary-processing.js
  src/services/forum-processing.js
  src/services/local-processing.js
  src/services/model/Log.js
  src/services/model/Summary.js
  src/vuex/store.js
Labels: enhancement, Task
